// Generated by dia2code
#ifndef STATE__ARROW__H
#define STATE__ARROW__H


namespace state {
  class Position;
  class Units;
}

#include "Position.h"
#include "IdTextureUnits.h"
#include "Units.h"

namespace state {

  /// class Arrow - 
  class Arrow : public state::Units {
    // Operations
  public:
    Arrow (int level, int id, Position p, int life, int damage, int strikeRange, int movingRange, IdTextureUnits idTextureUnits);
    // Setters and Getters
  };

};

#endif
