// Generated by dia2code
#ifndef STATE__ARROW__H
#define STATE__ARROW__H


namespace state {
  class Position;
  class Element;
  class Units;
}

#include "Position.h"
#include "Element.h"
#include "Units.h"

namespace state {

  /// class Arrow - 
  class Arrow : public state::Units {
    // Operations
  public:
    Arrow (int level, int id, int life, int damage, int strikeRange, int movingRange, int idTextureUnits);
    bool moveAllowed (Position p1, Position p2, int movingRange, int moveNumber);
    void move (Position p1, Position p2);
    void attack (Element unit1, Element unit2);
    bool attackAllowed (Element unit1, Element unit2, int strikeRange);
    // Setters and Getters
  };

};

#endif
