// Generated by dia2code
#ifndef STATE__BARRACK__H
#define STATE__BARRACK__H


namespace state {
  class Position;
  class Arrow;
  class Cavalier;
  class Decurion;
  class Catapult;
  class Buildings;
}

#include "Position.h"
#include "IdTexture.h"
#include "Arrow.h"
#include "Cavalier.h"
#include "Decurion.h"
#include "Catapult.h"
#include "Buildings.h"

namespace state {

  /// class Barrack - 
  class Barrack : public state::Buildings {
    // Attributes
  private:
    int capacity;
    int unitsNumber;
    // Operations
  public:
    Barrack ();
    Barrack (int capacity, int id, Position position, int level, IdTexture idTexture);
    int getCapacity () const;
    void setCapacity (int capacity);
    int  getUnitsNumber () const;
    void setUnitsNumber (int unitsNumber);
    /// switch case for units level. 
    /// @param level		(???) 
    /// @param position		(???) 
    /// @param id		(???) 
    Arrow createArrow (int level, Position position, int id);
    /// switch case for units level. 
    /// @param level		(???) 
    /// @param position		(???) 
    /// @param id		(???) 
    Cavalier createCavalier (int level, Position position, int id);
    /// switch case for units level. 
    /// @param level		(???) 
    /// @param position		(???) 
    /// @param id		(???) 
    Decurion createDecurion (int level, Position position, int id);
    Catapult createCatapult (int level, Position position, int id);
    // Setters and Getters
  };

};

#endif
