// Generated by dia2code
#ifndef STATE__BARRACK__H
#define STATE__BARRACK__H


namespace state {
  class Position;
  class Buildings;
}

#include "Position.h"
#include "Buildings.h"

namespace state {

  /// class Barrack - 
  class Barrack : public state::Buildings {
    // Attributes
  private:
    int capacity;
    // Operations
  public:
    Barrack (int capacity, int id, Position position, int level, int idTexture);
    int getCapacity ();
    void setCapacity (int capacity);
    /// switch case for units level. 
    void createArrow ();
    /// switch case for units level. 
    void createCavalier ();
    /// switch case for units level. 
    void createDecurion ();
    void createCatapult ();
    // Setters and Getters
  };

};

#endif
