// Generated by dia2code
#ifndef STATE__BUILDINGSOBSERVER__H
#define STATE__BUILDINGSOBSERVER__H

#include <memory>

namespace state {
  class Element;
  class Observable;
}

#include "Element.h"

namespace state {

  /// class BuildingsObserver - 
  class BuildingsObserver {
    // Operations
  public:
    void changeBuildings (std::unique_ptr<Element> buildingsMap, Observable& mapToChange, int position);
    // Setters and Getters
  };

};

#endif
