// Generated by dia2code
#ifndef STATE__BUILDINGOBSERVER__H
#define STATE__BUILDINGOBSERVER__H


namespace state {

  /// class BuildingObserver - 
  class BuildingObserver {
    // Operations
  public:
    void changeBuilding ();
    // Setters and Getters
  };

};

#endif
