// Generated by dia2code
#ifndef STATE__BUILDINGCOST__H
#define STATE__BUILDINGCOST__H


namespace state {

  /// class BuildingCost - 
  class BuildingCost {
    // Attributes
  private:
    int gold;
    int wood;
    // Operations
  public:
    BuildingCost (int gold, int wood);
    ~BuildingCost ();
    void setGold (int gold);
    int getGold () const;
    void setWood (int wood);
    int getWood () const;
    // Setters and Getters
  };

};

#endif
