// Generated by dia2code
#ifndef STATE__BUILDINGCOST__H
#define STATE__BUILDINGCOST__H


namespace state {

  /// class BuildingCost - 
  class BuildingCost {
    // Attributes
  private:
    unsigned int gold;
    unsigned  int wood;
    // Operations
  public:
    BuildingCost ();
    BuildingCost ( int gold, int wood);
    ~BuildingCost ();
    void setGold (const int gold);
    int getGold () const;
    void setWood (const int wood);
    int getWood () const;
    // Setters and Getters
  };

};

#endif
