// Generated by dia2code
#ifndef STATE__BUILDINGSOBSERVER__H
#define STATE__BUILDINGSOBSERVER__H


namespace state {
  class Observable;
  class Element;
}

#include "Element.h"

namespace state {

  /// class BuildingsObserver - 
  class BuildingsObserver {
    // Operations
  public:
    void changeBuildings (Observable& mapToChange, int position, int action, int unitToCreate, int position2);
    void changeBuildingsPrev (Observable& mapToChange, int position, int action, int unitToDestroy, int position2);
    // Setters and Getters
  };

};

#endif
