// Generated by dia2code
#ifndef STATE__BUILDINGSOBSERVER__H
#define STATE__BUILDINGSOBSERVER__H


namespace state {

  /// class BuildingsObserver - 
  class BuildingsObserver {
    // Operations
  public:
    void changeBuildings ();
    // Setters and Getters
  };

};

#endif
