// Generated by dia2code
#ifndef STATE__CATAPULT__H
#define STATE__CATAPULT__H


namespace state {
  class Position;
  class UnitCost;
  class Units;
}

#include "Position.h"
#include "IdTextureUnits.h"
#include "UnitCost.h"
#include "Units.h"

namespace state {

  /// class Catapult - 
  class Catapult : public state::Units {
    // Operations
  public:
    Catapult ();
    Catapult (int level, int id, Position position, int life, int damage, int strikeRange, int movingRange, IdTextureUnits idTextureUnits, UnitCost catapultCost);
    Catapult (int level, Position position, int id);
    ~Catapult ();
    // Setters and Getters
  };

};

#endif
