// Generated by dia2code
#ifndef STATE__CAVALIER__H
#define STATE__CAVALIER__H


namespace state {
  class Position;
  class Units;
}

#include "Position.h"
#include "IdTextureUnits.h"
#include "Units.h"

namespace state {

  /// class Cavalier - 
  class Cavalier : public state::Units {
    // Operations
  public:
    Cavalier ();
    Cavalier (int level, int id, Position position, int life, int damage, int strikeRange, int movingRange, IdTextureUnits idTextureUnits);
    Cavalier (int level, Position position, int id);
    ~Cavalier ();
    // Setters and Getters
  };

};

#endif
