// Generated by dia2code
#ifndef STATE__DECOR__H
#define STATE__DECOR__H


namespace state {
  class Position;
  class Element;
}

#include "IdDecor.h"
#include "Position.h"
#include "Element.h"

namespace state {

  /// class Decor - 
  class Decor : public state::Element {
    // Associations
    state::IdDecor idDecor;
    // Attributes
  private:
    bool passable;
    // Operations
  public:
    Decor ();
    Decor (IdDecor id, Position position);
    bool getPassable () const;
    void setPassable (bool passable);
    // Setters and Getters
    IdDecor getIdDecor() const;
    void setIdDecor(IdDecor idDecor);
  };

};

#endif
