// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Position;
}

#include "Position.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  protected:
    Position position;
    // Operations
  public:
    Element ();
    Element (Position position);
    ~Element ();
    bool isPassable ();
    Position& getPosition ();
    void setPosition (Position& position);
    int distance (Position pos1, Position pos2);
    // Setters and Getters
  };

};

#endif
