// Generated by dia2code
#ifndef STATE__IDDECOR__H
#define STATE__IDDECOR__H


namespace state {

  enum IdDecor {
<<<<<<< HEAD
    NONE     = 0,
=======
    NONE_DECOR     = 0,
>>>>>>> de7a7205cfb919cb1e85e327142c6750f70a621d
    ARBRE     = 1,
    CHEVAL     = 2,
    RENNE     = 3,
    POISSON     = 4,
    POULE     = 5,
    MONTAGNE     = 6,
    DUNE     = 7,
    HERBE     = 8,
    EAU     = 9
  };

};

#endif
