// Generated by dia2code
#ifndef STATE__IDDECOR__H
#define STATE__IDDECOR__H


namespace state {

  enum IdDecor {
    ARBRE     = 1,
    CHEVAL     = 2,
    RENNE     = 3,
    POISSON     = 4,
    POULES     = 5,
    MONTAGNE     = 6,
    DUNES     = 7,
    HERBE     = 8,
    EAU     = 9
  };

};

#endif
