// Generated by dia2code
#ifndef STATE__IDDECOR__H
#define STATE__IDDECOR__H


namespace state {

  enum IdDecor {
    NONE_DECOR     = 0,
    EAU     = 1,
    HERBE     = 2,
    MONTAGNE     = 3,
    CHEVAL     = 4,
    POULE     = 5,
    POISSON     = 6,
    RENNE     = 7,
    ARBRE     = 8,
    LIFE     = 9
  };

};

#endif
