// Generated by dia2code
#ifndef STATE__IDTEXTUREUNITS__H
#define STATE__IDTEXTUREUNITS__H


namespace state {

  enum IdTextureUnits {
    NONE_UNIT     = 0,
    DECURION1     = 10,
    DECURION2     = 11,
    DECURION3     = 12,
    DECURION4     = 13,
    ARROW1     = 14,
    ARROW2     = 15,
    ARROW3     = 16,
    ARROW4     = 17,
    CAVALIER1     = 18,
    CAVALIER2     = 19,
    CAVALIER3     = 20,
    CAVALIER4     = 21,
    CATAPULT1     = 22,
    CATAPULT2     = 23,
    CATAPULT3     = 24,
    CATAPULT4     = 25
  };

};

#endif
