// Generated by dia2code
#ifndef STATE__IDTEXTURE__H
#define STATE__IDTEXTURE__H


namespace state {

  enum IdTexture {
    NONE_BUILDING     = 0,
    HDV1     = 1,
    HDV2     = 2,
    HDV3     = 3,
    HDV4     = 4,
    BARRACK     = 5,
    RESSOURCE1     = 6,
    RESSOURCE2     = 7,
    RESSOURCE3     = 8
  };

};

#endif
