// Generated by dia2code
#ifndef STATE__IDTEXTURE__H
#define STATE__IDTEXTURE__H


namespace state {

  enum IdTexture {
    NONE_BUILDING     = 0,
    HDV1     = 26,
    HDV2     = 27,
    HDV3     = 28,
    HDV4     = 29,
    BARRACK     = 30,
    RESSOURCE1     = 31,
    RESSOURCE2     = 32,
    RESSOURCE3     = 33
  };

};

#endif
