// Generated by dia2code
#ifndef STATE__IDTEXTUREUNITS__H
#define STATE__IDTEXTUREUNITS__H


namespace state {

  enum IdTextureUnits {
    NONE_UNIT     = 0,
    DECURION1     = 1,
    DECURION2     = 2,
    DECURION3     = 3,
    DECURION4     = 4,
    ARROW1     = 5,
    ARROW2     = 6,
    ARROW3     = 7,
    ARROW4     = 8,
    CAVALIER1     = 9,
    CAVALIER2     = 10,
    CAVALIER3     = 11,
    CAVALIER4     = 12,
    CATAPULT1     = 13,
    CATAPULT2     = 14,
    CATAPULT3     = 15,
    CATAPULT4     = 16
  };

};

#endif
