// Generated by dia2code
#ifndef STATE__IDTEXTURE__H
#define STATE__IDTEXTURE__H


namespace state {

  enum IdTexture {
    RESSOURCE     = 1,
    BARRACK     = 2,
    HDV0     = 3,
    HDV1     = 4,
    HDV2     = 5,
    HVD3     = 6
  };

};

#endif
