// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H

#include <vector>
#include <memory>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Map - 
  class Map {
    // Associations
    // Attributes
  private:
    std::vector<std::unique_ptr<Element>> playingMap;
    // Operations
  public:
    Map ();
    ~Map ();
    void setMap (const std::vector<std::unique_ptr<Element>> playingMap);
    std::vector<std::unique_ptr<Element>> getMap ();
    // Setters and Getters
  };

};

#endif
