// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>
#include <memory>

namespace state {
  class Map;
  class Observable;
  class Element;
  class UnitsObserver;
  class BuildingsObserver;
}

#include "Map.h"
#include "Element.h"
#include "UnitsObserver.h"
#include "BuildingsObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  private:
    Map allMaps;
    std::vector<std::unique_ptr<Element>> ressurectionElement;
    // Operations
  public:
    ~Observable ();
    void notifyObserver (state::Observable& observable, int position, int idToChange, int action, int unitToCreate, int position2) const;
    void notifyObserverPrev (state::Observable& observable, int position, int idToChange, int action, int unitToDestroy, int position2) const;
    Observable ();
    Map& getAllMaps ();
    std::vector<std::unique_ptr<Element>>& getRessurectionElement ();
    void setRessurectionElement (std::vector<std::unique_ptr<Element>>& ressurectionElement);
    // Setters and Getters
  };

};

#endif
