// Generated by dia2code
#ifndef STATE__PALACE__H
#define STATE__PALACE__H


namespace state {
  class Position;
  class BuildingCost;
  class Buildings;
}

#include "Position.h"
#include "IdTexture.h"
#include "BuildingCost.h"
#include "Buildings.h"

namespace state {

  /// class Palace - 
  class Palace : public state::Buildings {
    // Operations
  public:
    Palace ();
    Palace (int id, Position position, int level, IdTexture idTexture, BuildingCost palaceCost);
    Palace (int id, Position position, int level);
    ~Palace ();
    // Setters and Getters
  };

};

#endif
