// Generated by dia2code
#ifndef STATE__RESSOURCE__H
#define STATE__RESSOURCE__H


namespace state {
  class Position;
  class Buildings;
}

#include "Position.h"
#include "IdTexture.h"
#include "Buildings.h"

namespace state {

  /// class Ressource - 
  class Ressource : public state::Buildings {
    // Attributes
  private:
    int production;
    // Operations
  public:
    Ressource ();
    Ressource (int production, int id, Position position, int level, IdTexture idTexture);
    void ressourceProduction (int gold, int wood, int food);
    int getProduction () const;
    void setProduction (int production);
    // Setters and Getters
  };

};

#endif
