// Generated by dia2code
#ifndef STATE__UNITSOBSERVER__H
#define STATE__UNITSOBSERVER__H


namespace state {

  /// class UnitsObserver - 
  class UnitsObserver {
    // Operations
  public:
    void changeUnits ();
    // Setters and Getters
  };

};

#endif
