// Generated by dia2code
#ifndef STATE__UNITSOBSERVER__H
#define STATE__UNITSOBSERVER__H


namespace state {
  class Observable;
  class Element;
}

#include "Element.h"

namespace state {

  /// class UnitsObserver - 
  class UnitsObserver {
    // Operations
  public:
    void changeUnits (Observable& mapToChange, int position, int action, int position2);
    void changeUnitsPrev (Observable& mapToChange, int position, int action, int position2);
    // Setters and Getters
  };

};

#endif
