// Generated by dia2code
#ifndef STATE__UNITS__H
#define STATE__UNITS__H


namespace state {
  class Position;
  class Units;
  class Element;
}

#include "Position.h"
#include "IdTextureUnits.h"
#include "Element.h"

namespace state {

  /// class Units - 
  class Units : public state::Element {
    // Associations
    state::IdTextureUnits idTextureUnits;
    // Attributes
  protected:
    int idUnits;
    int life;
    int damage;
    int strikeRange;
    int movingRange     = 1;
    int level;
    // Operations
  public:
    Units ();
    Units (int idUnits, Position position, int life, int damage, int strikeRange, int movingRange, int level, IdTextureUnits idTextureUnits);
    ~Units ();
    void setLife (int life);
    int getLife () const;
    void setDamage (int damage);
    int getDamage () const;
    void setStrikeRange (int strikeRange);
    int getStrikeRange () const;
    void setMovingRange (int movingRange);
    int getMovingRange () const;
    void move (Position& p2, int moveNumber);
    bool moveAllowed (Position p2, int moveNumber);
    void attack (Units& unit2);
    bool attackAllowed (Units unit2);
    int getLevel () const;
    void setLevel (int level);
    IdTextureUnits getIdTextureUnits () const;
    void setIdTextureUnits (IdTextureUnits idTextureUnits);
    int getIdUnits () const;
    void setIdUnits (int idUnits);
    // Setters and Getters
  };

};

#endif
