// Generated by dia2code
#ifndef STATE__UNITCOST__H
#define STATE__UNITCOST__H


namespace state {

  /// class UnitCost - 
  class UnitCost {
    // Attributes
  private:
    int gold;
    int food;
    // Operations
  public:
    UnitCost ();
    UnitCost (int gold, int food);
    ~UnitCost ();
    void setGold (int gold);
    int getGold () const;
    void setFood (int food);
    int getFood () const;
    // Setters and Getters
  };

};

#endif
