// Generated by dia2code
#ifndef STATE__UNITCOST__H
#define STATE__UNITCOST__H


namespace state {

  /// class UnitCost - 
  class UnitCost {
    // Attributes
  private:
    int gold;
    int food;
    // Operations
  public:
    UnitCost (int gold, int food);
    void setGold (int gold);
    int getGold ();
    void setFood (int food);
    int getFood ();
    // Setters and Getters
  };

};

#endif
