// Generated by dia2code
#ifndef STATE__UNITSOBSERVER__H
#define STATE__UNITSOBSERVER__H

#include <memory>

namespace state {
  class Element;
  class Observable;
}

#include "Element.h"

namespace state {

  /// class UnitsObserver - 
  class UnitsObserver {
    // Operations
  public:
    void changeUnits (std::unique_ptr<Element> mapUnits, Observable& mapToChange, int position, int action);
    // Setters and Getters
  };

};

#endif
