// Generated by dia2code
#ifndef RENDER__BUILDINGTILESET__H
#define RENDER__BUILDINGTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class BuildingTileSet - 
  class BuildingTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> palace;
    std::vector<Tile> barrack;
    std::vector<Tile> ressource;
    // Operations
  public:
    BuildingTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string& getImageFile () const;
    const Tile& getTile (const state::Element& e) const;
    // Setters and Getters
  };

};

#endif
