// Generated by dia2code
#ifndef RENDER__DECORTILESET__H
#define RENDER__DECORTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class DecorTileSet - 
  class DecorTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> decor;
    // Operations
  public:
    DecorTileSet ();
    ~DecorTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile getTile (const state::Element& e) const;
    // Setters and Getters
  };

};

#endif
