// Generated by dia2code
#ifndef RENDER__LAYERCREATOR__H
#define RENDER__LAYERCREATOR__H

#include <SFML/Graphics.hpp>
#include <string>
#include <vector>

namespace sf {
  class Text;
  class Font;
  class Texture;
  class VertexArray;
  class Color;
  class Transformable;
  class Drawable;
}


namespace render {

  /// class LayerCreator - 
  class LayerCreator : public sf::Transformable, public sf::Drawable {
    // Attributes
  public:
    sf::Text text;
    sf::Font font;
  private:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    LayerCreator ();
    LayerCreator (const std::string& imageFile, int size, std::vector<int> tiles);
    LayerCreator (const std::string& fontFile, std::string& text, int size, sf::Color& color, int x, int y);
    void loadTexture (const std::string& imageFile);
    void initQuads (int size);
    void setSpriteLocation (int size, int x, int y);
    void setSpriteTexture (int size, std::vector<int> tiles, int x, int y);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    void loadFont (const std::string& fontFile);
    void setFont ();
    void setText (std::string& text);
    void setCharacterSize (int size);
    void setColor (sf::Color& color);
    void setPosition (int x, int y);
    sf::Text getText () const;
    // Setters and Getters
  };

};

#endif
