// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H


namespace render {
  class MapCreator;
  class TileSet;
};
namespace state {
  class Map;
}

#include "MapCreator.h"
#include "TileSet.h"
#include "state/Map.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  private:
    MapCreator basicMap;
    MapCreator decorMap;
    MapCreator buildingMap;
    // Operations
  public:
    Layer ();
    ~Layer ();
    MapCreator getBuildingMap () const;
    MapCreator getBasicMap () const;
    MapCreator getDecorMap () const;
    // Setters and Getters
  };

};

#endif
