// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <memory>
#include <string>
#include <stdlib.h>

namespace render {
  class MapCreator;
  class TileSet;
}

#include "MapCreator.h"
#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    std::unique_ptr<MapCreator> mapCreator;
    std::shared_ptr<TileSet> tileset;
    // Operations
  public:
    Layer ();
    ~Layer ();
    const MapCreator* const getMapCreator ();
    void setMapCreator (MapCreator* mapCreator);
    virtual void initMapCreator ();
    void printText (int x, int y, const std::string& msg, size_t tileMinIdx, size_t tileMaxIdx);
    void setTileSet (std::shared_ptr<TileSet> tileSet);
    const std::shared_ptr<TileSet> getTileSet () const;
    // Setters and Getters
    const std::shared_ptr<TileSet>& getTileset() const;
    void setTileset(const std::shared_ptr<TileSet>& tileset);
  };

};

#endif
