// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <SFML/Graphics.hpp>
#include <string>
#include <vector>

namespace sf {
  class Text;
  class Font;
  class Texture;
  class VertexArray;
  class Sprite;
  class Color;
  class RenderWindow;
  class Transformable;
  class Drawable;
}


namespace render {

  /// class Layer - 
  class Layer : public sf::Transformable, public sf::Drawable {
    // Attributes
  public:
    sf::Text text;
    sf::Font font;
  private:
    sf::Texture texture;
    sf::VertexArray quads;
    sf::Sprite background;
    // Operations
  public:
    Layer ();
    Layer (const std::string& imageFile, int size, std::vector<int> tiles, int iso);
    Layer (const std::string& fontFile, std::string text, int size, sf::Color color, int x, int y);
    Layer (const std::string& imageFile);
    ~Layer ();
    void loadTexture (const std::string& imageFile);
    void initQuads (int size);
    void setSpriteLocation (int size, int x, int y, int iso);
    void setSpriteTexture (int size, std::vector<int> tiles, int x, int y, int iso);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    void loadFont (const std::string& fontFile);
    void setFont ();
    void setText (std::string& text);
    void setCharacterSize (int size);
    void setColor (sf::Color& color);
    void setPosition (int x, int y);
    sf::Text getText () const;
    void drawText (sf::RenderWindow& window) const;
    void drawSprite (sf::RenderWindow& window) const;
    // Setters and Getters
  };

};

#endif
