// Generated by dia2code
#ifndef RENDER__MAPLAYER__H
#define RENDER__MAPLAYER__H


namespace state {
  class Map;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/Map.h"

namespace render {

  /// class MapLayer - 
  class MapLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::Map& map;
    // Operations
  public:
    MapLayer (const state::Map& map);
    void initMapCreator ();
    // Setters and Getters
  };

};

#endif
