// Generated by dia2code
#ifndef RENDER__MENULAYER__H
#define RENDER__MENULAYER__H

#include <string>

namespace sf {
  class Text;
};
namespace render {
  class MapCreator;
}

#include "MapCreator.h"

namespace render {

  /// class MenuLayer - 
  class MenuLayer : public render::MapCreator {
    // Attributes
  private:
    sf::Text text;
    sf::Font font;
    // Operations
  public:
    MenuLayer (const std::string& fontFile, std::string text, int size, sf::Color color, int x, int y);
    void loadFont (const std::string& fontFile);
    void setFont ();
    void setText (std::string text);
    void setCharacterSize (int size);
    void setColor (sf::Color color);
    void setPosition (int x, int y);
    // Setters and Getters
  };

};

#endif
