// Generated by dia2code
#ifndef RENDER__RENDERMAP__H
#define RENDER__RENDERMAP__H


namespace render {
  class Layer;
  class TileSet;
};
namespace state {
  class Map;
}

#include "Layer.h"
#include "TileSet.h"
#include "state/Map.h"

namespace render {

  /// class renderMap - 
  class renderMap {
    // Associations
    // Attributes
  private:
    Layer basicMap;
    Layer decorMap;
    Layer buildingMap;
    Layer unitMap;
    Layer statsMap;
    Layer* background;
    // Operations
  public:
    renderMap ();
    ~renderMap ();
    Layer getBuildingMap () const;
    Layer getBasicMap () const;
    Layer getDecorMap () const;
    Layer getUnitMap () const;
    Layer getStatsMap () const;
    Layer* getBackground () const;
    // Setters and Getters
  };

};

#endif
