// Generated by dia2code
#ifndef RENDER__STATSTILESET__H
#define RENDER__STATSTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Decor;
}

#include "Tile.h"

namespace render {

  /// class StatsTileSet - 
  class StatsTileSet {
    // Attributes
  private:
    std::vector<Tile> level;
    Tile life;
    // Operations
  public:
    StatsTileSet ();
    ~StatsTileSet ();
    const std::string getImageFile () const;
    const Tile getTile (const state::Decor& e) const;
    // Setters and Getters
  };

};

#endif
