// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    virtual ~TileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    virtual const std::string getImageFile () const = 0;
    // Setters and Getters
  };

};

#endif
