// Generated by dia2code
#ifndef RENDER__UNITSTILESET__H
#define RENDER__UNITSTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Units;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"
#include "state/Units.h"

namespace render {

  /// class UnitsTileSet - 
  class UnitsTileSet : public render::TileSet {
    // Associations
    // Attributes
  private:
    std::vector<Tile> arrow;
    std::vector<Tile> cavalier;
    std::vector<Tile> decurion;
    std::vector<Tile> catapult;
    // Operations
  public:
    UnitsTileSet ();
    ~UnitsTileSet ();
    const std::string getImageFile () const;
    const Tile getTile (const state::Units& e) const;
    // Setters and Getters
  };

};

#endif
