// Generated by dia2code
#ifndef RENDER__UNITSTILESET__H
#define RENDER__UNITSTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class UnitsTileSet - 
  class UnitsTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> arrow;
    std::vector<Tile> cavalier;
    std::vector<Tile> decurion;
    std::vector<Tile> catapult;
    // Operations
  public:
    UnitsTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string& getImageFile () const;
    const Tile& getTile (const state::Element& e) const;
    // Setters and Getters
  };

};

#endif
