// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace state {
  class Observable;
};
namespace engine {
  class Engine;
}

#include "state/Observable.h"
#include "engine/Engine.h"

namespace ai {

  /// class AI - 
  class AI {
    // Associations
    // Setters and Getters
  };

};

#endif
