// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace engine {
  class Engine;
}

namespace ai {

  /// class AI - 
  class AI {
    // Operations
  public:
    virtual void run (engine::Engine& engine) = 0;
    // Setters and Getters
  };

};

#endif
