// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace engine {
  class Engine;
}

#include "engine/Engine.h"

namespace ai {

  /// class AI - 
  class AI {
    // Associations
    // Operations
  public:
    virtual void run (engine::Engine& engine) = 0;
    // Setters and Getters
  };

};

#endif
