// Generated by dia2code
#ifndef AI__DEEPAI__H
#define AI__DEEPAI__H


namespace engine {
  class Engine;
};
namespace state {
  class Observable;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class DeepAI - 
  class DeepAI : public ai::AI {
    // Operations
  public:
    DeepAI ();
    void run (engine::Engine& engine, state::Observable& principalMap, int& counter, bool& canPlay, int id);
    // Setters and Getters
  };

};

#endif
