// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace engine {
  class Engine;
};
namespace state {
  class Observable;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Operations
  public:
    HeuristicAI ();
    void run (engine::Engine& engine, state::Observable& principalMap, int& counter, bool& canPlay, int id);
    // Setters and Getters
  };

};

#endif
