// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H


namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Attributes
  private:
    int randNumber;
    // Operations
  public:
    RandomAI ();
    void run (engine::Engine& engine, Observable& principalMap, int& counter, bool& canPlay, int id);
    // Setters and Getters
  };

};

#endif
