// Generated by dia2code
#ifndef ENGINE__ATTACK__H
#define ENGINE__ATTACK__H


namespace state {
  class Observable;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class Attack - 
  class Attack : public engine::Command {
    // Attributes
  private:
    state::Observable& map;
    int x;
    int y;
    int x2;
    int y2;
    // Operations
  public:
    ~Attack ();
    CommandTypeId getTypeId () const;
    void execute ();
    // Setters and Getters
  };

};

#endif
