// Generated by dia2code
#ifndef ENGINE__CASEIDENTIFIER__H
#define ENGINE__CASEIDENTIFIER__H


namespace engine {

  /// class CaseIdentifier - 
  class CaseIdentifier {
    // Setters and Getters
  };

};

#endif
