// Generated by dia2code
#ifndef ENGINE__CLICK__H
#define ENGINE__CLICK__H


namespace state {
  class Position;
}

#include "state/Position.h"

namespace engine {

  /// class Click - 
  class Click {
    // Attributes
  private:
    state::Position positionTile;
    // Setters and Getters
  };

};

#endif
