// Generated by dia2code
#ifndef ENGINE__CLICK__H
#define ENGINE__CLICK__H


namespace engine {

  /// class Click - 
  class Click {
    // Operations
  public:
    Click ();
    // Setters and Getters
  };

};

#endif
