// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    CASEIDENTIFIER     = 1,
    PRINTSTATS     = 2,
    POSSIBILITIES     = 3,
    MOVE     = 4,
    ATTACK     = 5,
    LEVELUP     = 6,
    CREATEUNIT     = 7
  };

};

#endif
