// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace state {
  class Observable;
}

#include "CommandTypeId.h"
#include "state/Observable.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getTypeId () const;
    // Setters and Getters
  };

};

#endif
