// Generated by dia2code
#ifndef ENGINE__CREATEUNIT__H
#define ENGINE__CREATEUNIT__H


namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CreateUnit - 
  class CreateUnit : public engine::Command {
    // Operations
  public:
    ~CreateUnit ();
    CommandTypeId getTypeId () const;
    void execute ();
    // Setters and Getters
  };

};

#endif
