// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


namespace sf {
  class Drawable;
  class Transformable;
  class Font;
  class RenderWindow;
  class Texture;
  class Color;
  class Text;
  class Sprite;
  class VertexArray;
};
namespace render {
  class RenderMap;
};
namespace state {
  class Observable;
};
namespace engine {
  class Command;
}

#include "render/RenderMap.h"
#include "state/Observable.h"
#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Operations
  public:
    Engine ();
    ~Engine ();
    // Setters and Getters
  };

};

#endif
