// Generated by dia2code
#ifndef ENGINE__LEVELUP__H
#define ENGINE__LEVELUP__H


namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class LevelUp - 
  class LevelUp : public engine::Command {
    // Operations
  public:
    ~LevelUp ();
    CommandTypeId getTypeId () const;
    void execute ();
    // Setters and Getters
  };

};

#endif
