// Generated by dia2code
#ifndef ENGINE__MOVE__H
#define ENGINE__MOVE__H


namespace state {
  class Observable;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class Move - 
  class Move : public engine::Command {
    // Attributes
  private:
    int x;
    int y;
    int x2;
    int y2;
    // Operations
  public:
    ~Move ();
    CommandTypeId getTypeId () const;
    void execute (state::Observable& principalMap);
    void rollback (state::Observable& principalMap);
    Move (int x, int y, int x2, int y2);
    // Setters and Getters
  };

};

#endif
