// Generated by dia2code
#ifndef ENGINE__POSIBILITIES__H
#define ENGINE__POSIBILITIES__H


namespace engine {

  /// class Posibilities - 
  class Posibilities {
    // Setters and Getters
  };

};

#endif
