// Generated by dia2code
#ifndef ENGINE__POSSIBILITIES__H
#define ENGINE__POSSIBILITIES__H


namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class Possibilities - 
  class Possibilities : public engine::Command {
    // Operations
  public:
    ~Possibilities ();
    CommandTypeId getTypeId () const;
    void execute ();
    // Setters and Getters
  };

};

#endif
