// Generated by dia2code
#ifndef ENGINE__POSSIBILITIES__H
#define ENGINE__POSSIBILITIES__H


namespace state {
  class Observable;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class Possibilities - 
  class Possibilities : public engine::Command {
    // Operations
  public:
    ~Possibilities ();
    CommandTypeId getTypeId () const;
    void execute (state::Observable& map, int x, int y, int element);
    // Setters and Getters
  };

};

#endif
