// Generated by dia2code
#ifndef ENGINE__PRINTSTATS__H
#define ENGINE__PRINTSTATS__H


namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class PrintStats - 
  class PrintStats : public engine::Command {
    // Operations
  public:
    ~PrintStats ();
    CommandTypeId getTypeId () const;
    void execute ();
    // Setters and Getters
  };

};

#endif
