// Generated by dia2code
#ifndef SERVER__COMMAND__H
#define SERVER__COMMAND__H


namespace server {

  /// class Command - 
  class Command {
    // Attributes
  public:
    int num;
    int id;
    int x;
    int y;
    int x2;
    int y2;
    int unit;
    int element;
    // Operations
  public:
    Command (int num, int id, int x, int y, int x2, int y2, int unit, int element);
    // Setters and Getters
  };

};

#endif
