// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H


namespace server {

  /// class Player - 
  class Player {
    // Attributes
  public:
    string name;
    int type;
    int tour;
    // Operations
  public:
    Player (string name, int type, int tour);
    // Setters and Getters
  };

};

#endif
