// Generated by dia2code
#ifndef SERVER__PLAYERDB__H
#define SERVER__PLAYERDB__H

#include <string>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class PlayerDB - 
  class PlayerDB {
    // Associations
    // Attributes
  protected:
    int idseq;
    map<int,unique_ptr<Player> > players;
    // Operations
  public:
    PlayerDB ();
    const Player* getPlayer (int id) const;
    int addPlayer (unique_ptr<Player> player);
    void setPlayer (int id, unique_ptr<Player> player);
    void removePlayer (int id);
    std::string getAllPlayer ();
    // Setters and Getters
    int getIdseq() const;
    void setIdseq(int idseq);
    const map<int,unique_ptr<Player> >& getPlayers() const;
    void setPlayers(const map<int,unique_ptr<Player> >& players);
  };

};

#endif
