#include "./stateTest/PositionTest.h"
#include "./stateTest/ElementTest.h"
#include "./stateTest/UnitsTest.h"
#include "./stateTest/ArrowTest.h"
#include "./stateTest/CatapultTest.h"
#include "./stateTest/CavalierTest.h"
#include "./stateTest/DecurionTest.h"
