// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <memory>
#include <mutex>
#include <SFML/Graphics.hpp>
#include <string>

namespace engine {
  class Engine;
};
namespace state {
  class Observable;
};
namespace render {
  class RenderMap;
};
namespace ai {
  class HeuristicAI;
}

#include "engine/Engine.h"
#include "state/Observable.h"
#include "render/RenderMap.h"
#include "ai/HeuristicAI.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  public:
    std::condition_variable renderCV;
  private:
    engine::Engine engine;
    std::unique_ptr<state::Observable> principalMap;
    render::RenderMap map;
    ai::HeuristicAI heuristic;
    std::mutex engineMutex;
    std::mutex renderMutex;
    std::condition_variable engineCV;
    // Operations
  public:
    Client ();
    void run ();
    void engineUpdating (sf::RenderWindow& window, bool& canPlay1, bool& canPlay2, bool& canPlay3, bool& palace1, bool& palace2, bool& palace3, int& counter, int& id, int& idPalace, std::string& gold, std::string& wood, std::string& food, state::Empire* empire1, state::Empire* empire2, state::Empire* empire3, int& stop);
    void engineUpdated ();
    ai::HeuristicAI getHeuristic ();
    // Setters and Getters
  };

};

#endif
