// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/MapCreator.h"
#include "render/Tile.h"
#include "render/TileSet.h"
#include "render/Layer.h"
#include "render/MapLayer.h"
#include "render/DecorTileSet.h"
#include "render/UnitsTileSet.h"
#include "render/BuildingTileSet.h"
#endif
